#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 20 12:45:40 2020

@author: Mana
"""

import pandas as pd

from matplotlib import pyplot as plt

x = [1,3,3]
y = [1,4,9]
z= [10,5,9]
plt.plot(x,y)
